<?php
session_start();
error_reporting(E_ALL & ~E_NOTICE);
include __DIR__ . '/KonFunctions.php';
$campaign_path = "https://" . $_SERVER['SERVER_NAME'];
$ssl_url = "https://" . $_SERVER['SERVER_NAME'];

$folder_name = '';

$shipping_id = '';
$campaign_id = 7;
$api_key_user = 'maglifeapi-86715';
$api_key_pass = 'J%b^b1)g^n(gfNId)71l85rc';
$productArray = array(
    141 => array(
        'id' => 141,
        'name' => 'MagLife Bracelet - 1 Unit 33% OFF',
        'success_redirect' => $ssl_url . '/up1.php',
        'img' => './assets/images/mb-price-box-grid-img-3.png',
        'page' => "step2.php",
//        'sku' => 'TLFB-Q1-P1',
        'qty' => 1,
        'price' => 29.99),
/*    149 => array(
        'id' => 149,
        'name' => 'test',
        'success_redirect' => $ssl_url . '/up1.php',
        'img' => './assets/images/mb-price-box-grid-img-3.png',
        'page' => "step2.php",
        'qty' => 1,
        'price' => 0.01),*/
    142 => array(
        'id' => 142,
        'name' => 'MagLife Bracelet - 2 Units 44% OFF',
        'success_redirect' => $ssl_url . '/up1.php',
        'img' => './assets/images/mb-price-box-grid-img-1.png',
        'page' => "step2.php",
//        'sku' => 'TLFB-Q3-P1',
        'qty' => 1,
        'price' => 49.99),
    143 => array(
        'id' => 143,
        'name' => 'MagLife Bracelet - 4 Units 56% OFF',
        'success_redirect' => $ssl_url . '/up1.php',
        'img' => './assets/images/mb-price-box-grid-img-2.png',
        'page' => "step2.php",
//        'sku' => 'TLFB-Q6-P1',
        'qty' => 1,
        'price' => 78.99),
    144 => array(
        'id' => 144,
        'name' => 'MagLife Bracelet - 4 Units (Special Offer)',
        'success_redirect' => $ssl_url . '/up2.php',
        'img' => './assets/images/upsell-slider-img-1.jpg',
        'page' => "up1.php",
        'qty' => 1,
        'price' => 59.96),
/*    150 => array(
        'id' => 150,
        'name' => 'test',
        'success_redirect' => $ssl_url . '/up2.php',
        'img' => './assets/images/mb-price-box-grid-img-3.png',
        'page' => "up1.php",
        'qty' => 1,
        'price' => 0.01),*/
    145 => array(
        'id' => 145,
        'name' => 'MagLife Bracelet - 2 Units (Special Offer)',
        'success_redirect' => $ssl_url . '/up2.php',
        'img' => './assets/images/upsell-slider-img-1.jpg',
        'page' => "ds1.php",
        'qty' => 1,
        'price' => 29.99),
    146 => array(
        'id' => 146,
        'name' => 'MagLife Insoles - 2 Pairs (Special Offer)',
        'success_redirect' => $ssl_url . '/up3.php',
        'img' => './assets/images/upsell-two-grid-lft-img-3.jpg',
        'page' => "up2.php",
        'qty' => 1,
        'price' => 39.99),
    147 => array(
        'id' => 147,
        'name' => 'MagLife Insoles - 1 Pair (Special Offer)',
        'success_redirect' => $ssl_url . '/up3.php',
        'img' => './assets/images/upsell-two-grid-lft-img-3.jpg',
        'page' => "ds2.php",
        'qty' => 1,
        'price' => 19.99),
    148 => array(
        'id' => 148,
        'name' => 'Lifetime Warranty',
        'success_redirect' => $ssl_url . '/thank-you.php',
        'img' => './assets/images/upsell-two-grid-lft-img-5.png',
        'page' => "up3.php",
        'qty' => 1,
        'price' => 10.00),
);

$custom_product_price = 0.00;
$currency_text = 'USD';